### ISSUE TITLE
project development TODO

### ISSUE THREAD

**Issue by seoyeong200** [seoyeong98/Book-data-Pipeline#1]
## description

현재 데이터 ETL 을 돌릴 수 있는 정도의 시스템이다.
어떤 식으로 확장할 수 있을까 생각해보면, 현재 책을 추천하는 방식이 spark application을 하나 실행하면 user X의 Book Y에 대한 similar book 의 결과 띵 찍고 종료되기 때문에,
이 user X, Book Y 받고 결과 반환하는 주고받기를 api로 디벨롭시키면 더 완성도가 높아질 것 같다. FastAPI 아니면 Flask 쓰면 될듯

**Comment by seoyeong200** [comment]
#TODO

- [x] 데이터 재수집
    - [x] 로컬에 수집 or 클라우드 수집? 
    - 윈도우 깔다가 펌웨어 꼬여서 맥북 공장초기화한 여성을 아시나요? 그 사람이 .. 바로 나에요...
    - 데이터 진짜 싸그리 다 날라갔다. 로컬 스토리지 260GB 정도 남아있음, 6코어 메모리 16GB, 로컬 성능도 나쁘지 않은데 계속 발열이 나서 걱정되긴 한다. aws 람다 + rdb써서 데이터 스크래핑은 클라우드로 돌려서 클라우드 디비에 적재되게끔 돌리고, 로컬 스쿱으로 클라우드 디비 접근해서 local fs에 파일화해서 적재하는건 어떨까 하는 생각이 든다
    - 그럼 일단 이거 구현 도전 진짜 클라우드 잘끄자 !!!!! 클라우드 잘 꺼라 잘 꺼라 ........


- [x] execute by command line -> make into script file
- [x] ipynb notebook file to py script
- [x] 개발환경 compose file, 배포(?)환경 compose file 각각 생성하기
    - 개발환경 - jupyter+spark, 배포환경 - spark

- [ ] api
    - [ ] user info 받는 method
    - [ ] 책 받는 method -> 추천 결과 반환하는 method

**Comment by seoyeong200** [comment]
1. 데이터 수집 단계 refactoring

- Scraping
    - [x] aws lambda 함수 작성 (데이터 스크래핑 스크립트)
- DB setting
    - [x] 관계형db 하나 세팅해서 여기에 수집
        - aws lambda 에 도커 컨테이너로 mysql 세팅하는게 나을까? vs AWS RDS 쓰는게 나을까?
        - 람다에 mysql 컨테이너 배포하면 어차피 aws ecr(컨테이너 레지스트리) 써야하고 저장 공간에 따라 과금되긴한다
        - container : lambda + ECR
        - solution : lambda + RDS
- cloud - local 네트워크 연결, 보안 설정

**Comment by seoyeong200** [comment]
## 뒷단 (S3 to API)
#### 1. S3에 scrapped data

> dynamo->spark vs dynamo->s3->spark?

dynamo -> spark
👍 추가적으로 파이프라인 개발 안해도됨
👎 dynamodb 읽기 연산에 과금, 데이터가 주마다 배가 되므로 비용이 계속 증가할 것
👎 네트워크 지연이나 처리 속도 지연될 수 있음

s3 -> spark ✅
👍 s3에서 데이터 읽는게 dynamo보다 비용 적게 들 수 있음
👍 s3는 대량 데이터를 빠르게 읽는데 최적화된 스토리지기 때문에 효율적으로 읽기 가능
👎 추가 파이프라인 개발 필요
👎 dynamo에서 s3로 이동되는 시간이 지연

- [x] glue - dynamodb, s3 연결, 스케줄 설정
- [x] s3로 데이터 dumping

#### 2. S3 -> spark(processing) -> local filesystem
    - processing ) 줄거리 문서로부터 Word2Vec 모델 train
    - ~or using pretrained model~ -> db에 있는 데이터로 학습하는게 갖고있는 데이터 기준 추천에 용이할 것
    -  vector 정보 추가된 데이터 로컬에 parquet로 save
    - just file rather than database


#### 3. api 
    - GET method ) book title -> recommended books  
    - restAPI (fastapi)
    - 1) book exists in database -> (how) -> result
    - 2) book don't exist in database -> naver book api -> result forwarding

**Comment by seoyeong200** [comment]
- [x] dynamo -> s3 현재 glue로 파이프라인 만들어둔 것 aws cli로 바꾸는 것 고려
    - 현재 glue는 단순 화요일 오후 6시에 dynamo table이 s3 버킷으로 export 되도록 구성됨
    - 데이터 수집 작업이 완료된 사실은 로컬에서 프로세스 종료 여부로 확인할 수 있기 때문에 이후 aws cli로 export한다면 파이프라인 작업 간에 더 유기적인 연결이 될 수 있을 것 같다.
    -  해당 방법을 채택한다면 dynamo->s3 스크립트 만들기
- [x] spark에서 모델링 더 디벨롭 해보기
    - 추천 성능을 더 뛰어나게 만들 수 있는 방법이 뭐가 있을지 연구
    - [x] 모델, 벡터화된 데이터 local fs에 parquet 로 저장
    - [x] 책 a 들어왔을 때 책 간 유사도 계산, 비슷한 책 반환하는 스크립트 로직 작성
- [ ] 결과 반환 api
    - 비슷한 책 계산된 것 반환 api 개발
```
batch calculation
- vectorize 'description' string column -> 'model' column
- model column : each element is 1*100 DenseVector
- calculate similarity with each other(n*n) and get top 5 book_id in each book record
- this is the similar book id of book i

request ; bookA
if book A is in DataBase:
    return calculated result which is the info of similar books with book A
else:
    vectorize, calculate similarity, return top 5 in parallel(concurrency level is 2 due to theres 2 spark workers)
```
- [ ] 문서화
    - 그냥 처음부터 다시 다 개발했다고 봐도 무방한데... 잘 정리하자 차근차근

**Comment by seoyeong200** [comment]
## further development
테스트 코드 작성해보기,  Infra as Code 테라폼 사용해서 선언형으로 인프라 작성해보기

- [ ] spark processing unit testing code
- [ ] laC - terraform
