### ISSUE TITLE
Data Processing with Spark

### ISSUE THREAD

**Issue by seoyeong200** [seoyeong98/Book-data-Pipeline#11]
## Read Data as spark dataframe from s3 using spark sql api

로컬에서 spark docker cluster를 띄워서 s3에 있는 데이터에 접근해서 spark sql api dataframe형태로 읽는다.
향후 해당 데이터로 모델 학습 및 결과를 내는데, 한가지 문제점이 있다.
s3 uri를 spark.read 메소드 인자로 넣어주는데, 이 uri 즉 dynamo table로부터 export된 데이터가 위치한 경로 이름이 랜덤으로 생성되어 static하게 지정해둘 수 없고 계속 조정을 해줘야한다는 점이다.

이걸 자동화(?) 하려면 
- 람다를 사용해서 data is exported to s3 이런 이벤트를 트리거로 걸어놓고,
- 해당 데이터를 내가 원하는 경로로 이동시키고,
- 이 경로이름을 spark script에서 static하게 참조하도록 하는것이다.
뭔가 데이터가 수집돼어 s3로 export된 date를 경로명으로 줘서 관리하고 spark에서도 수집날짜 경로명을  활용해서 데이터 transformation이 되었으면 좋겠는데..

근데 생각해보면 spark cluster 띄우고 spark job을 실행시키는걸 자동화할것인가? 라고 했을때 no기 때문에, 
저 작업을 굳이 추가해야할까? 싶긴 하다

**Comment by seoyeong200** [comment]
## model examination

#### 문제 정의
Lets' say theres
문서 집합 A : 책들의 description column, list of string elements
새로운 책의 줄거리 문서 x - string
Then
x를 수치화하고, x와 가장 유사한 문서들을 찾기


#### 적용 가능한 솔루션들 
[Finding similar documents](https://fastdatascience.com/finding-similar-documents-nlp/)
- bag of words
- Word2Vec
    - 단어들 임베딩. 단어 간 유시성 계산 가능
    - 따라서 현재 문제 상황인 단어 집합 간의 유사성을 찾고싶으면 이후 작업이 필요함
    - 1. 각 책에 대해 평균 벡터값 구하기 : 책 A가 갖고있는 단어 집합의 모든 단어에 대한 벡터를 가져와서 평균 계산 -> 모든 책에 대해 반복, avg_vector 컬럼의 값으로 저장 -> 책 A와 B의 유사도 = avg_vector의 cosine similarity value
    - 2. 벡터 공간에서 가까운 이웃 찾기 : 단어 집합에 대한 평균 벡터까지 동일 -> 모델의 전체 단어 벡터 중 이 평균 벡터와 가장 가까운 단어들 찾기


- Doc2Vec
    - spark에 구현, 내장되어있지 않기 때문에, 파이썬 Gensim 라이브러리 사용해야함
<details><summary>source code reference</summary>

```python
from gensim.models.doc2vec import Doc2Vec, TaggedDocument
from nltk.tokenize import word_tokenize

documents = ["This is a sample sentence", "This is another sample sentence"]

# TaggedDocument 객체 생성
tagged_data = [TaggedDocument(words=word_tokenize(doc.lower()), tags=[str(i)]) for i, doc in enumerate(documents)]

# Doc2Vec 모델 학습
model = Doc2Vec(vector_size=20, alpha=0.025, min_alpha=0.00025, min_count=1, dm=1)
model.build_vocab(tagged_data)

# 모델 학습 (여러번 반복)
for epoch in range(10):
    model.train(tagged_data, total_examples=model.corpus_count, epochs=model.epochs)
    model.alpha -= 0.0002  # 학습률 감소
    model.min_alpha = model.alpha

# 모델 저장
model.save("d2v.model")

## 문서 간 유사성 계산
# 모델 로드
model = Doc2Vec.load("d2v.model")

# 새로운 문서 벡터화
new_document = "This is a new sentence"
new_vector = model.infer_vector(word_tokenize(new_document.lower()))

# 가장 유사한 문서 찾기
similar_documents = model.docvecs.most_similar([new_vector])
print(similar_documents)

``` 

</details>
- Transformers

**Comment by seoyeong200** [comment]
#### todo
- [x] 전처리 - 스크래핑 잘 안된 데이터 제거(null 컬럼 제거) - test
- [x] cluster 환경에서 테스트
    - [x] w2v codebase to script
    - [x] script test - run on a cluster
    - [ ] vector or similar books list  저장 (to database or file or whatever)


#### udf 작성 시 유의할 점
평균 벡터 구하는 udf 작성
spark cluster의 모든 노드에 필요한 라이브러리(gensim, numpy)가 설치되어있어야한다.
udf 호출시마다 모델 로드하는 것보다 모델을 메모리에 한번만 로드하고 재사용하는 방법을 고려하는게 필요
udf는 spark의 최적화된 변환 연산보다 효울이 떨어질수 있다.

<details><summary>진짜 고민이 ....</summary>

1:n 계산
현재 책의 줄거리 문자열 -> 벡터 까지는 개발 완료.

그럼 이제 이걸 어떻게 해야하는거지..?
모델 저장 - 로컬경로에 파일로 저장
로컬 다이나모 디비에 넣는 내용 ? bid-vectors
새로운 책 줄거리에 대해서 word2vec으로 벡터로 변환하고 vectors - vector 코사안 계산,(1:n 계산) -> 그럼 전체 책에 대해 n번의 계산이 api 호출할 떄마다 발생한다는건데 이게 맞나...??///  유사도 높은 bid 5개 a, b, c, d, e뽑아서

아니 연산이 너무 무거워지는데..?
api 호출 (줄거리 x)
1. word2vec 모델 메모리에 올리고
2. x -> vector_x
3. vector_x랑 전체 vectors에 대해 코사인 유사도 게산
4. top 5개의 bid 갖고오기
5. 해당 bid에 해당하는 나머지 정보들(title, author, image, description) 쿼리해서 갖고오기
6. 해당 정보 응답으로 반환

이건 어떨까
- 현재 db에 있는 책에 대해서만 유사한 책 리턴하고
- db에 없는 책이면 gpt를 태우던 naver book api 를 태우던 하거나, 최악의 경우 데이터베이스에 없는챡이라는 응답을 반환하는거야.
- 그래서 db에는 {bid: 비슷한 책 리스트들} 저장해놓고 이 결과 반환하는거지
- 그리고 이 db에 없는 책이면 다른 api 태우고 

이렇게 하면 해야될게
- 책 - 책 간 유사도 구하기 : n * n 의 연산
- 이게 진짜 대용량이라고 가정하면 여러 노드에 분산 저장되어있을텐데 파티셔닝 기준을 잘 잡야야할듯
- 유사도가 높은 것들끼리 최대한 모여있도록 하고싶은데 어떻게 해야하지?

</details>

**Comment by seoyeong200** [comment]
### test
- 수집한 책 데이터로 W2V 모델 학습시키고,
- 해당 모델로 토큰화된 description 컬럼인 preprocessed 컬럼을 vectorize한 model 컬럼을 생성
- 책 하나 뽑아서 다른 모든 벡터들 간 코사인 유사도 계산, 높은 유사도를 갖는 상위 10개의 도서 뽑아봄
```test book
title='제주 오름 트레킹 가이드'
category='테마여행'
description='오르면 오를수록 마음이 푸르러진다, 놀멍 쉬멍 걷기 좋은 제주 오름 124곳!  
친환경 제주 여행을 선사하는 다정한 안내서, 『제주 오름 트레킹 가이드』  변하지 않는 것은 오직 자연이다. 
제주의 이름난 명소들, 식당과 카페, 해변과 올레길을 차례로 순례했다면 이제는 오름에 눈을 돌릴 때다. 
오름은 하나의 작고 오롯한 제주다. 오름을 오르다 보면 제주도의 탄생 원리와 역사, 고유의 독특한 문화, 경이로운 생태계를 쉼 없이 맞닥뜨린다. 
『제주 오름 트레킹 가이드』는 124개의 눈부신 오름을 망라해 최적의 여행법을 소개한다. 제주를 대표하는 랜드마크 오름, 경유하기 좋은 올레길, 연계 여행하기 좋은 탐방 코스, 마을 산책 정보를 꼼꼼하게 제공해 초보 여행자부터 트레킹 숙련자까지 모두가 이 책을 통해 오름과 즐겁게 만날 수 있다.'

```
    - category 컬럼 기준으로 파티셔닝 한 상위 10개의 책
```
+--------+--------------------------------+----------------------------------+-----------------+--------+---------------------------------+--------------------+----+----------------------------------+------------------------------+--------------------+----------+---------------+
|     bid|                           title|                          subtitle|           author|category|                      description|               image|rank|                      remove_noise|                  preprocessed|               model|     coSim|similarity_rank|
+--------+--------------------------------+----------------------------------+-----------------+--------+---------------------------------+--------------------+----+----------------------------------+------------------------------+--------------------+----------+---------------+
|17191293|          한국의 골프장 이야기 2| 코스의 속삭임까지 받아 적은 우...|         '류석무'|    골프|우리나라 명문 골프장들의 코스,...|'[https://shopping...|](https://shopping...%7C/)  28| 우리나라 명문 골프장들의 코스 ...|[우리나라, 명문, 골프장, 코...|[0.05578651540847...| 0.5395991|              1|
|16348535|  골프로 인생을 설계할 수 있다면|     오상준의 인생역전 골프 에세이|         '오상준'|    골프| 건축가이자 골프코스 설계가, G...|'[https://shopping...|](https://shopping...%7C/)  28|  건축가이자 골프코스 설계가 GO...| [건축가, 이자, 골프, 코스,...|[0.06037601494366...|0.51252663|              2|
|18121157|       한국의 골프장 이야기 세트| 코스의 속삭임까지 받아 적은 우...|  '류석무,남화영'|    골프|우리나라 명문 골프장들의 코스,...|'[https://shopping...|](https://shopping...%7C/)  28| 우리나라 명문 골프장들의 코스 ...|[우리나라, 명문, 골프장, 코...|[0.05211031373861...|  0.507469|              3|
|15477586|          한국의 골프장 이야기 1| 코스의 속삭임까지 받아 적은 우...|  '류석무,남화영'|    골프|우리나라 명문 골프장들의 코스,...|'[https://shopping...|](https://shopping...%7C/)  28| 우리나라 명문 골프장들의 코스 ...|[우리나라, 명문, 골프장, 코...|[0.05367303430929...|0.49715596|              4|
|22447645|          한국의 골프장 이야기 3| 코스의 속삭임까지 받아 적은 우...|         '류석무'|    골프|     “100번 쳐본 사람보다 (이 ...|'[https://shopping...|](https://shopping...%7C/)   7|   번 쳐본 사람보다 이 책 보고 ...|  [번, 치다, 보다, 사람, 이...|[0.05623184531150...|0.49539557|              5|
|22463744| 한국의 골프장 이야기 1~3권 세트| 코스의 속삭임까지 받아 적은 우...|  '류석무,남화영'|    골프|     한국 대표 100개 골프장 - ...|'[https://shopping...|](https://shopping...%7C/)   7|   한국 대표 개 골프장  명문과 ...|  [한국, 대표, 개, 골프장, ...|[0.05486815402198...|0.49416858|              6|
|21350528|                  매혹, 골프라는|                                  |         '이종현'|    골프|아침에 일어나면 얼굴 솜털을 일...|'[https://shopping...|](https://shopping...%7C/)   7| 아침에 일어나면 얼굴 솜털을 일...|[아침, 일어나다, 얼굴, 솜털...|[0.04025156397943...|0.48829365|              7|
|22067469|               천사골퍼 악마골퍼|  그린 위에서 매너와 싱글을 한 ...|  '정현권,김명선'|    골프|동반자에게 여운을 남기는 매너 ...|'[https://shopping...|](https://shopping...%7C/)   7| 동반자에게 여운을 남기는 매너 ...| [동반, 여운, 남기다, 매너,...|[0.03847209940593...|0.42699412|              8|
|17355609|          방민준의 골프 오디세이|                                  |         '방민준'|    골프| -골프야말로 모순덩어리다. 이 ...|'[https://shopping...|](https://shopping...%7C/)  28|골프야말로 모순덩어리다 이 세상...|  [골프, 덩어리, 이, 세상, ...|[0.03459000611096...| 0.3853314|              9|
|22311194|골프 라운드 전에 꼭 읽어야 할 책|    최소 10타 줄여주는 실전 솔루션|'스가와라 다이치'|    골프| “연습장에서 치는 공과 실전에 ...|'[https://shopping...|](https://shopping...%7C/)   7| 연습장에서 치는 공과 실전에 나...| [연습장, 치다, 공과, 실전,...|[0.03316437782148...| 0.3432743|             10|
|13571651|      파크골프 교본: Park Gol...|             Park Golf 이론과 실제|         '오명근'|    골프|        파크골프(Park Golf)는 ...|'[https://shopping...|](https://shopping...%7C/)  49|        파크골프Park Golf는 년 ...|  [파크, 골프, 늘다, 년, 전...|[0.06005385914613...| 0.3275668|             11|
| 7688487| 한국의 명 방파제 낚시터: 동해편|                                  |  '예조원 편집부'|    낚시| ‘짜릿하고 맛있는 방파제’를 캐...|'[https://shopping...|](https://shopping...%7C/)  52|짜릿하고 맛있는 방파제를 캐치프...|[짜릿하다, 맛있다, 방파제, ...|[0.05408989988370...| 0.7378273|              1|
|14082780|                  현대 낚시 교본|                                  | '현대레저연구회'|    낚시| 누구나 알기 쉬운 바다 낚시 강...|'[https://shopping...|](https://shopping...%7C/)  10|  누구나 알기 쉬운 바다 낚시 강...|  [누구, 알다, 쉽다, 바다, ...|[0.02072292514882...|0.67443967|              2|
| 6933646|                로드 빌딩 길잡이|      내 손으로 직접 만드는 낚싯대|         '윤종호'|    낚시|낚시 마니아들을 위한 최첨단 로...|'[https://shopping...|](https://shopping...%7C/)  52| 낚시 마니아들을 위한 최첨단 로...| [낚시, 마니아, 위, 최첨단,...|[0.03118458084012...| 0.6606047|              3|
|14618175|       하늘에서 본 낚시터 대백과|  경기ㆍ강원 충청편 | 초정밀 항...|'낚시춘추 편집부'|    낚시|항공사진 낚시터 시리즈 제2탄인...|'[https://shopping...|](https://shopping...%7C/)  10| 항공사진 낚시터 시리즈 제탄인 ...|[항공사진, 낚시터, 시리즈, ...|[0.03753526056124...|0.61494124|              4|
|16418638|       하늘에서 본 방파제 낚시터|                                  |'낚시춘추 편집부'|    낚시|〈하늘에서 본 방파제 낚시터〉 ...|'[https://shopping...|](https://shopping...%7C/)  10| 하늘에서 본 방파제 낚시터 발간...|[하늘, 보다, 방파제, 낚시터...|[0.03137356377956...|0.59950453|              5|
|13834663|                        원투낚시|            낭만과 힐링의 바다낚시|'낚시춘추 편집부'|    낚시|최근 바다낚시 가운데 가장 핫한...|'[https://shopping...|](https://shopping...%7C/)  10| 최근 바다낚시 가운데 가장 핫한...|[최근, 바다낚시, 가운데, 가...|[0.03298406963867...|0.58879244|              6|
| 9137696|                  현대 낚시 교본|  누구나 알기 쉬운 바다 낚시 강...| '현대레저연구회'|    낚시|  [현대 낚시 교본]은 누구나 알...|'[https://shopping...|](https://shopping...%7C/)  31|  현대 낚시 교본은 누구나 알기 ...|  [현대, 낚시, 교본, 누구, ...|[0.01173519292351...| 0.5815129|              7|
|20851063|                        캠핑낚시|                                  |         '서성모'|    낚시|코로나시대 최고의 힐링레저로  ...|'[https://shopping...|](https://shopping...%7C/)  10| 코로나시대 최고의 힐링레저로  ...| [코로나, 시대, 최고, 힐링,...|[0.02899408906183...| 0.5791834|              8|
| 7202723|                 낚시를 시작하다|푸르른 바다에 낚싯대를 드리우고...|         '김지민'|    낚시| 낚시로 소소한 일탈을 즐기자! ...|'[https://shopping...|](https://shopping...%7C/)  52|  낚시로 소소한 일탈을 즐기자  ...|[낚시, 소소하다, 탈, 즐기다...|[0.02743537276595...|0.57042325|              9|
+--------+--------------------------------+----------------------------------+-----------------+--------+---------------------------------+--------------------+----+----------------------------------+------------------------------+--------------------+----------+---------------+
```
category 값이 같은(테마여행) 책들 중 cos_sim 값이 높은 애들 뽑아보면 꽤나 비슷해보이는 책들을 뽑아준다.
```
+--------------------------------+--------+-----------------------------------+--------------------+----------+---------------+
|                           title|category|                        description|               model|     coSim|similarity_rank|
+--------------------------------+--------+-----------------------------------+--------------------+----------+---------------+
|         제주 오름 트레킹 가이드|테마여행| 오르면 오를수록 마음이 푸르러진...|[0.06748670876153...|       1.0|              1|
|       제주 걷기 여행(2022~2023)|테마여행| 올레부터 한라산까지 제주 걷기코...|[0.08722614178259...| 0.9685754|              2|
|지하철로 떠나는 서울 & 근교 여행|테마여행|  지하철 노선 속에 숨겨진 매력적...|[0.04997887825251...| 0.9340469|              3|
|              타박타박 서울 유람|테마여행|   일상에 작은 여행 한 스푼 타박...|[0.05715233866482...| 0.9198191|              4|
|         대한민국 섬 여행 가이드|테마여행|    떠나자, 바다로, 섬으로! 걷고...|[0.05627905540184...|0.91644824|              5|
|일상이 고고학, 나 혼자 제주 여행|테마여행|   기존 제주 여행의 관념을 뚫고,...|[0.09431820580114...| 0.9038298|              6|
|             오름 오름 트레킹 맵|테마여행|   오름에 반할 준비가 된 용감한 ...|[0.05927985534626...|0.88747585|              7|
|        대한민국 드라이브 가이드|테마여행|   목적지를 향해 가는 최단 거리 ...|[0.03848267012085...| 0.8861279|              8|
|                       오름 오름|테마여행|  오름은 언제나 옳다. 어디에서도...|[0.03876707056440...| 0.8795979|              9|
|         우리는 숲으로 여행 간다|테마여행|       2022, 지금 가장 핫한 전국...|[0.04029848549319...|0.87486994|             10|
|          대한민국 트레킹 가이드|테마여행|여행전문작가와 산악전문가가 만든...|[0.07758236733428...|  0.873831|             11|
+--------------------------------+--------+-----------------------------------+--------------------+----------+---------------+
```
    - 그냥 전체 상위 5개 🛑 -> description이 영어인 경우 그냥 W2V모델을 통해 vectorize하면 빈 벡터값을 갖게 되기 때문에 cos_sim 컬럼값이 다 널값으로 채워지고, 비슷한 책이 아닌 그냥 영어 도서들 뽑아옴
    - 1. description 영어면 한글로 번역해서 같이 학습시킨다.
    - 2. 그냥 냅두고 cos_sim 컬럼 값 널값인 경우는 similarity 계산에서 제외시킨다.
```
+--------+------------------------------+-------------------------------+-----------------------+---------------+--------------------+--------------------+----+--------------------+------------+-----------+-----+---------------+
|     bid|                         title|                       subtitle|                 author|       category|         description|               image|rank|        remove_noise|preprocessed|      model|coSim|similarity_rank|
+--------+------------------------------+-------------------------------+-----------------------+---------------+--------------------+--------------------+----+--------------------+------------+-----------+-----+---------------+
| 4661751|          France, 8/e Paper...|                               |     'Nicola, Williams'| 철학/심리/역사|Discover France D...|'[https://shopping...|](https://shopping...%7C/)  49|Discover France D...|          []|(100,[],[])|  NaN|              1|
|11696519|세계 명작 소설 노트 : 이솝 ...|           A Novel Journal :...|               '이영옥'| 철학/심리/역사|Aesop was a slave...|'[https://shopping...|](https://shopping...%7C/)  28|Aesop was a slave...|          []|(100,[],[])|  NaN|              1|
| 2941096|          The Gardener : 19...|           1998 Caldecott Honor|        '사라 스튜어트'|      문학/소설|By the author-and...|'[https://shopping...|](https://shopping...%7C/)  49|By the authorandi...|          []|(100,[],[])|  NaN|              1|
|14434970|          Discrete Mathemat...|                               |        'Susanna S.Epp'| 과학/공학/수학|DISCRETE MATHEMAT...|'[https://shopping...|](https://shopping...%7C/)  25|DISCRETE MATHEMAT...|          []|(100,[],[])|  NaN|              1|
| 6746340|          Treasury of Greek...|           Classic Stories o...|     'Napoli, Donna Jo'|      종교/명상|School Library Jo...|'[https://shopping...|](https://shopping...%7C/)  46|School Library Jo...|          []|(100,[],[])|  NaN|              1|
|20554943|                       Framers|           Human Advantage i...|   'Kenneth Cukier,V...|         컴퓨터|As humans we are ...|'[https://shopping...|](https://shopping...%7C/)  10|As humans we are ...|          []|(100,[],[])|  NaN|              1|
| 9753399|          The Language of F...|           A Linguist Reads ...|        '댄 주래프스키'|           요리|2015 James Beard ...|'[https://shopping...|](https://shopping...%7C/)   1| James Beard Awar...|          []|(100,[],[])|  NaN|              1|
|12879703|                       A Paris|                               |      'Bastide, Lauren'|         프랑스|It-girl au demi-m...|'[https://shopping...|](https://shopping...%7C/)   7|Itgirl au demimil...|          []|(100,[],[])|  NaN|              1|
| 6793587|          Pantone Postcard ...|                  100 Postcards|         'Pantone Inc.'|      취미/여행|With a palette dr...|'[https://shopping...|](https://shopping...%7C/)  46|With a palette dr...|          []|(100,[],[])|  NaN|              1|
|12471361|          Creepy Pair of Un...|                               |        '에런 레이놀즈'|       경영경제|From the celebrat...|'[https://shopping...|](https://shopping...%7C/)   1|From the celebrat...|          []|(100,[],[])|  NaN|              1|
| 7710287|          DK Children’s Ill...|                               |                   'DK'|       경영경제|Never be lost for...|'[https://shopping...|](https://shopping...%7C/)  43|Never be lost for...|          []|(100,[],[])|  NaN|              1|
|18002392|          Virgil Abloh. Nik...|  버질 아블로 x 나이키 아이콘스|        'Abloh, Virgil'|      건축/예술|Nike and Virgil A...|'[https://shopping...|](https://shopping...%7C/)  13|Nike and Virgil A...|          []|(100,[],[])|  NaN|              1|
| 8996200|          The 13-Story Tree...|                 Monkey Mayhem!|        '앤디 그리피스'|      문학/소설|Andy and Terry li...|'[https://shopping...|](https://shopping...%7C/)   7|Andy and Terry li...|          []|(100,[],[])|  NaN|              1|
| 9079275|          Mary Poppins Pape...|                    메리 포핀스|   'Travers, P. L.,S...|       경영경제|With a brand new ...|'[https://shopping...|](https://shopping...%7C/)  22|With a brand new ...|          []|(100,[],[])|  NaN|              1|
|17664662|          The Art of Star W...|’스타워즈: 만달로리안 시즌 1...|         'Abrams Books'|      건축/예술|This official beh...|'[https://shopping...|](https://shopping...%7C/)  13|This official beh...|          []|(100,[],[])|  NaN|              1|
|15556672|          1000 Basic Englis...|                               |        'Kelli Ripatti'|유아청소년/교육|Publico al que va...|'[https://shopping...|](https://shopping...%7C/)   1|Publico al que va...|          []|(100,[],[])|  NaN|              1|
| 9219299|                  Being Mortal|           Illness, Medicine...|          '아툴 가완디'|      종교/명상|From the internat...|'[https://shopping...|](https://shopping...%7C/)  25|From the internat...|          []|(100,[],[])|  NaN|              1|
|21978177|          Owl Diaries #16 :...|           A Branches Book (...|     'Elliott, Rebecca'|   사회/정치/법|Eva Wingdale has ...|'[https://shopping...|](https://shopping...%7C/)  10|Eva Wingdale has ...|          []|(100,[],[])|  NaN|              1|
|13952079|                       Feed Me|                               |       'Prola, Liviana'|      가족/생활|An informative an...|'[https://shopping...|](https://shopping...%7C/)  10|An informative an...|          []|(100,[],[])|  NaN|              1|
|15754407|          World Atlas of Wi...|     『월드 아틀라스 와인』원서|'잰시스 로빈슨,휴 존슨'|           요리|A major new editi...|'[https://shopping...|](https://shopping...%7C/)   1|A major new editi...|          []|(100,[],[])|  NaN|              1|
+--------+------------------------------+-------------------------------+-----------------------+---------------+--------------------+--------------------+----+--------------------+------------+-----------+-----+---------------+
```
